discord.py
python-dotenv
peewee
```

To create this file:
1. Open your project in PyCharm
2. Right-click on the project root
3. New -> File
4. Name it `requirements.txt`
5. Paste the contents above
6. Save the file

For GitHub Actions, you'll also want to create a workflow file:


name: Discord Bot Continuous Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Discord Bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: python run.py
